# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-cu-vars
- group: common-pipeline-vars
- name: kubernetesNamespace
  value: development
- name: helmConfigName
  value: $(kubernetesNamespace)-$(regionCode)-values


steps:

- bash: |
    echo dockerHubRepositoryName $(dockerHubRepositoryName)
    echo helmRepository $(helmRepository)
    echo helmGitCredentials $(helmGitCredentials)
    echo dockerRegistry $(dockerRegistry)
    echo helmConfigName $(helmConfigName)
  displayName: 'var tests'

