# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master 

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-cu-vars
- group: common-pipeline-vars
- name: kubernetesNamespace
  value: development
- name: helmConfigName
  value: $(kubernetesNamespace)-$(regionCode)-values

stages:
- stage: buildAndPushContainers

  jobs:
  - job: buildAndPush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'mkbru-dockerhub'
        repository: 'mkbru/app-server'
        command: 'buildAndPush'
        Dockerfile: '**/app-server/Dockerfile'
        tags: '2.0.0-$(Build.SourceVersion)'

  # jobs:    
  #   - job: buildAndPushRRAppServer
  #     steps:       
  #     - task: Docker@2
  #       inputs:
  #         containerRegistry: 'rr-dockerhub'
  #         repository: 'rotorooter/rr-app-server'
  #         command: 'build'
  #         Dockerfile: '**/rr-app-server/Dockerfile'
  #         tags: '$(Build.SourceVersion)'


  #   - job: buildAndPushRRAdminCMS
  #     steps:
  #     - task: Docker@2
  #       inputs:
  #         containerRegistry: 'rr-dockerhub'
  #         repository: 'rotorooter/rr-admin-cms'
  #         command: 'build'
  #         Dockerfile: '**/rr-admin-cms/Dockerfile'
  #         tags: '$(Build.SourceVersion)'


  #   - job: buildAndPushRRCloudNativeWeb
  #     steps:
  #     - task: Docker@2
  #       inputs:
  #         containerRegistry: 'rr-dockerhub'
  #         repository: 'rotorooter/rr-cloud-native-web'
  #         command: 'build'
  #         Dockerfile: '**/rr-cloud-native-web/Dockerfile'
  #         tags: '$(Build.SourceVersion)'

  #   - job: buildAndPushRRContentLayer
  #     steps:
  #     - task: Docker@2
  #       inputs:
  #         containerRegistry: 'rr-dockerhub'
  #         repository: 'rotorooter/rr-content-layer'
  #         command: 'build'
  #         Dockerfile: '**/rr-content-layer/Dockerfile'
  #         tags: '$(Build.SourceVersion)'