# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master 

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-cu-vars
- group: common-pipeline-vars
- name: kubernetesNamespace
  value: development
- name: helmConfigName
  value: $(kubernetesNamespace)-$(regionCode)-values

# stages:
# - stage: buildAndPushContainers

jobs:
- job: vars
  steps:
  -  bash: |
      echo $(GitVersion.SemVer)
      echo $(Build.SourceVersion)
      set TestVar=$(Build.SourceVersion)
      set MyCustomVar= %TestVar:~0,7%
      echo %MyCustomVar%
  displayName: 'vars'


    
  # - job: buildAndPushRRAppServer
  #   steps:
  #   - bash: |
  #       echo dockerHubRepositoryName = $(dockerHubRepositoryName)
  #       git rev-parse --short HEAD
  #       echo building docker image
  #       echo pushing docker image to repo
  #     displayName: 'build and push rr-app-server'

  # - job: buildAndPushRRAdminCMS
  #   steps:
  #   - bash: |
  #       echo dockerHubRepositoryName = $(dockerHubRepositoryName)
  #       git rev-parse --short HEAD
  #       echo building docker image
  #       echo pushing docker image to repo
  #     displayName: 'build and push rr-admin-cms'

  # - job: buildAndPushRRCloudNativeWeb
  #   steps:
  #   - bash: |
  #       echo dockerHubRepositoryName = $(dockerHubRepositoryName)
  #       git rev-parse --short HEAD
  #       echo building docker image
  #       echo pushing docker image to repo
  #     displayName: 'build and push rr-cloud-native-web'

  # - job: buildAndPushRRContentLayer
  #   steps:
  #   - bash: |
  #       echo dockerHubRepositoryName = $(dockerHubRepositoryName)
  #       git rev-parse --short HEAD
  #       echo building docker image
  #       echo pushing docker image to repo
  #     displayName: 'build and push rr-content-layer'