# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  name: environment
  type: string

variables:
  template: myvariabletemplate.yml

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: ls
  displayName: 'show folder contents'

- bash: |
    cd app-server
    cat Dockerfile
    echo Build Image
    echo Push Image to Repo
  displayName: 'build app-server'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
